### ISSUE TITLE
Missing files again

### ISSUE THREAD

**Issue by mrkal666** [sestain/cdn#2]
`Downloading https://github.com/sestain/cdn/raw/main/csgo//sound/levels_ranks/levelup.mp3.bz2.
Error downloading https://github.com/sestain/cdn/raw/main/csgo//sound/levels_ranks/levelup.mp3.bz2
Downloading https://github.com/sestain/cdn/raw/main/csgo//sound/levels_ranks/levelup.mp3.
Error downloading https://github.com/sestain/cdn/raw/main/csgo//sound/levels_ranks/levelup.mp3
Downloading https://github.com/sestain/cdn/raw/main/csgo//sound/levels_ranks/leveldown.mp3.bz2.
Error downloading https://github.com/sestain/cdn/raw/main/csgo//sound/levels_ranks/leveldown.mp3.bz2
Downloading https://github.com/sestain/cdn/raw/main/csgo//sound/levels_ranks/leveldown.mp3.
Error downloading https://github.com/sestain/cdn/raw/main/csgo//sound/levels_ranks/leveldown.mp3`

pleas fixa

**Comment by sestain** [comment]
Missing files added
